// auto gen
export enum Assets {
  'bed' = 'bed',
  'board' = 'board',
  'box' = 'box',
  'camera' = 'camera',
  'celldoor' = 'celldoor',
  'celldoor2' = 'celldoor2',
  'cop2idle' = 'cop2idle',
  'cop2run1' = 'cop2run1',
  'cop2run2' = 'cop2run2',
  'copidle' = 'copidle',
  'coprun1' = 'coprun1',
  'coprun2' = 'coprun2',
  'desk' = 'desk',
  'doorblue' = 'doorblue',
  'doorgreen' = 'doorgreen',
  'doorholder' = 'doorholder',
  'doorred' = 'doorred',
  'ground' = 'ground',
  'key' = 'key',
  'keyblue' = 'keyblue',
  'keygreen' = 'keygreen',
  'keyred' = 'keyred',
  'line' = 'line',
  'officedoorblue' = 'officedoorblue',
  'officedoorgreen' = 'officedoorgreen',
  'officedoorred' = 'officedoorred',
  'panel' = 'panel',
  'pipesblue' = 'pipesblue',
  'pipesgreen' = 'pipesgreen',
  'pipesred' = 'pipesred',
  'playeridle' = 'playeridle',
  'playerrun1' = 'playerrun1',
  'playerrun2' = 'playerrun2',
  'popup' = 'popup',
  'shadow' = 'shadow',
  'table1' = 'table1',
  'table2' = 'table2',
  'toppanel' = 'toppanel',
  'wallblue' = 'wallblue',
  'wallgreen' = 'wallgreen',
  'wallgrey' = 'wallgrey',
  'wallred' = 'wallred',
}

export type AssetName = keyof typeof Assets;
